version: "3.9"
name: "bancar-system"
services:
  postgres:
    image: postgres:17.0-alpine3.20
    env_file:
      - .env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./../:/usr/src/app
      - BancarSystem-data:/var/lib/postgresql/data
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  server:
    image: node:22-alpine
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      # Prisma native connection string
      DATABASE_URL: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@host.docker.internal:$POSTGRES_PORT/$POSTGRES_DB?schema=public"
    volumes:
      - ./../:/usr/src/app
    working_dir: /usr/src/app
    links:
      - postgres
    depends_on: 
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/sh","-c"]
    command: 
      - |
        npm install
        npx prisma migrate dev --name init
    

volumes:
  BancarSystem-data: